language: scala

scala:
   - 2.10.4
python:
   - 3.4
   
env:
  - EVALUATOR_DIR=scala/Evaluator
script:
  - cd $EVALUATOR_DIR && sbt assembly

install:
- pip install coveralls

after_success:
  - coveralls
